# frozen_string_literal: true

source 'http://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'rspec'
gem 'faker'
gem 'mongo'
gem 'selenium-webdriver'
gem 'selenium-cucumber'
gem 'chromedriver-installer'
gem 'chromedriver-helper'
gem 'geckodriver-helper'
gem 'headless'
gem 'fastri'
gem 'rcodetools'